.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. waltercoin_qt test_waltercoin_qt
clean: FORCE
	$(MAKE) -C .. waltercoin_qt_clean test_waltercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_waltercoin_qt_check
waltercoin-qt waltercoin-qt.exe: FORCE
	 $(MAKE) -C .. waltercoin_qt
apk: FORCE
	$(MAKE) -C .. waltercoin_qt_apk
